title: Amalion Publishing
description: ""
footer_text: Copyright 2021 Amalion
header_feature_image: ../uploads/headerbackfull.jpg
header_text: Amalion
header_text_color: "#ffffff"
bannerheight: 40vmax
logo: ../uploads/lionlogo.jpg
favicon: ../uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
