header_feature_image: ""
title: Amalion
description: Amalion is a multilingual independent academic publishing house
  based in Dakar, Senegal. / Amalion est une maison d’édition indépendante
  multilingue basée à Dakar, Sénégal.
footer_text: Copyright 2021 Amalion
logo: ../uploads/lionlogo.jpg
gridlayout: true
fixednavbar: true
showpencil: true
bannerheight: 10vmax
favicon: ../uploads/favicon.ico
