header_feature_image: ""
title: Amalion
description: ""
footer_text: Copyright 2021 Amalion
logo: ../uploads/lionlogo.jpg
gridlayout: true
fixednavbar: true
showpencil: true
bannerheight: 10vmax
favicon: ../uploads/favicon.ico
