header_feature_image: ""
title: Amalion Publishing
description: ""
footer_text: Copyright 2021 Amalion
logo: ../uploads/lionlogo.jpg
gridlayout: true
fixednavbar: true
bannerheight: 10vmax
favicon: ../uploads/favicon.ico
header_text: Amalion
