header_feature_image: ""
title: Amalion Publishing
description: ""
footer_text: Copyright 2021 Amalion
logo: ../uploads/lionlogo.jpg
favicon: ../uploads/favicon.ico
gridlayout: true
items: []
fixednavbar: true
bannerheight: 10vmax
header_text: Amalion
