header_feature_image: ""
title: Amalion
description: Amalion is a multilingual independent academic publishing house
  based in Dakar, Senegal. / Amalion est une maison d’édition indépendante
  multilingue basée à Dakar, Sénégal.
footer_text: © 2022 Amalion | <a class="privacy" href="/privacy/">Privacy Policy</a>
logo: ../uploads/lionhead-trans.png
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: true
showpencil: false
bannerheight: 10vmax
