header_feature_image: ""
title: Amalion
description: Amalion is a multilingual independent academic publishing house
  based in Dakar, Senegal. / Amalion est une maison d’édition indépendante
  multilingue basée à Dakar, Sénégal.
footer_text: © 2021 Amalion. <a href="/privacy/">Privacy Policy</a>
logo: ../uploads/lionhead-trans.png
gridlayout: true
fixednavbar: true
showpencil: true
bannerheight: 10vmax
favicon: ../uploads/favicon.ico
