header_feature_image: ""
title: Amalion Publishing
description: ""
footer_text: Copyright 2021 Amalion
logo: ../uploads/lionlogo.jpg
favicon: ../uploads/favicon.ico
gridlayout: true
items: []
header_text_color: "#a60000"
fixednavbar: true
bannerheight: 10vmax
header_text: Amalion
